In [2]:
import torch
import numpy as np

print(torch.__version__)
print(numpy.__version__)

2.9.1+cu128
2.3.2


In [3]:
tensor = torch.rand(4,3) # Create random 4 by 3 torch Tensor
tensor

tensor([[0.1992, 0.7385, 0.3336],
        [0.9474, 0.7496, 0.2595],
        [0.0476, 0.7648, 0.5422],
        [0.2721, 0.6520, 0.1154]])

In [4]:
# We can verify something is torch tensor by using type method
type(tensor)

torch.Tensor

In [5]:
# Torch Tensors are NumPy Arrays with the ability to be executed on GPUs
numpy_from_tensor = tensor.numpy()
numpy_from_tensor

array([[0.19923198, 0.73851573, 0.33364785],
       [0.94740176, 0.74958277, 0.25954223],
       [0.04761976, 0.7647771 , 0.54220235],
       [0.2721305 , 0.6520137 , 0.11536562]], dtype=float32)

In [ ]:
type(numpy_from_tensor) # Now we can see numpy type

numpy.ndarray

In [7]:
# Can also use to check in code the torch.is_tensor() method ex:
torch.is_tensor(tensor)

True

In [8]:
torch.is_tensor(numpy_from_tensor)

False

In [9]:
# The NumPy array and the PyTorch tensor share the same underlying memory
numpy_from_tensor[0, 0] = 100.0
numpy_from_tensor

array([[1.00000000e+02, 7.38515735e-01, 3.33647847e-01],
       [9.47401762e-01, 7.49582767e-01, 2.59542227e-01],
       [4.76197600e-02, 7.64777124e-01, 5.42202353e-01],
       [2.72130489e-01, 6.52013719e-01, 1.15365624e-01]], dtype=float32)

In [ ]:
tensor # See the first element was also changed her

tensor([[1.0000e+02, 7.3852e-01, 3.3365e-01],
        [9.4740e-01, 7.4958e-01, 2.5954e-01],
        [4.7620e-02, 7.6478e-01, 5.4220e-01],
        [2.7213e-01, 6.5201e-01, 1.1537e-01]])

In [11]:
# Now let's do the reverse and go from numpy arr to tensor
numpy_arr = np.array([[1.0, 2.0, 3.0],
                      [10.0, 20.0, 30.0],
                      [100.0, 200.0, 300.0]])
numpy_arr

array([[  1.,   2.,   3.],
       [ 10.,  20.,  30.],
       [100., 200., 300.]])

In [12]:
tensor_from_numpy = torch.from_numpy(numpy_arr)
tensor_from_numpy

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]], dtype=torch.float64)

In [13]:
type(tensor_from_numpy)

torch.Tensor

In [14]:
torch.is_tensor(tensor_from_numpy)

True

In [ ]:
# Changes to tensor are still reflected in numpy array since still same memory

In [15]:
# Torch allows you to initiate from numpy in others way too
np_array_one = np.array([4, 8])
np_array_one

array([4, 8])

In [16]:
tensor_from_array_one = torch.as_tensor(np_array_one)
# Performs a copy if the data is not already a tensor
tensor_from_array_one

tensor([4, 8])

In [17]:
np_array_one[1] = 5
tensor_from_array_one
# We can see it is still updated when original np array was changed

tensor([4, 5])

In [18]:
# We can also create a copy to create a new tensor
np_array_two = np.array([2, 2])
tensor_from_array_two = torch.tensor(np_array_two)
tensor_from_array_two

tensor([2, 2])

In [ ]:
np_array_two[1] = 4
tensor_from_array_two # see it did not get updated!

tensor([2, 2])