In [1]:
import torch
print(torch.__version__)

2.9.1+cu128


In [ ]:
# Create a random tensor to use
random_tensor = torch.Tensor([[10, 8, 30], [40, 5, 6], [12, 2, 21]])
random_tensor

tensor([[10.,  8., 30.],
        [40.,  5.,  6.],
        [12.,  2., 21.]])

In [ ]:
sorted_tensor, sorted_indices = torch.sort(random_tensor)
sorted_tensor # Has the same shape as the original

tensor([[ 8., 10., 30.],
        [ 5.,  6., 40.],
        [ 2., 12., 21.]])

In [ ]:
sorted_indices # Shows what elements changed ex 0 , 1, 2 first row is now 1, 0, 2 indices

tensor([[1, 0, 2],
        [1, 2, 0],
        [1, 0, 2]])

In [5]:
tensor_float = torch.FloatTensor([-1.1, -2.2, 3.3])
tensor_float

tensor([-1.1000, -2.2000,  3.3000])

In [6]:
# Get the abs value of the tensor
tensor_abs = torch.abs(tensor_float)
tensor_abs

tensor([1.1000, 2.2000, 3.3000])

In [8]:
rand1 = torch.abs(torch.randn(2, 3))
rand2 = torch.abs(torch.randn(2, 3))

In [9]:
# Like numpy we can add simply by calling the '+' operation
add1 = rand1 + rand2
add1

tensor([[3.1686, 1.9849, 2.1270],
        [2.0231, 1.9932, 0.5607]])

In [10]:
# Element wise addition we can use torch.add like so
add2 = torch.add(rand1, rand2)
add2

tensor([[3.1686, 1.9849, 2.1270],
        [2.0231, 1.9932, 0.5607]])

In [11]:
# Can divide element-wise each element of tensor by tensor + 0.3 for ex
tensor = torch.Tensor([[-1, -2, -3], 
                       [1, 2, 3]])
tensor_div = torch.div(tensor, tensor + 0.3)
tensor_div

tensor([[1.4286, 1.1765, 1.1111],
        [0.7692, 0.8696, 0.9091]])

In [12]:
# Multiplication: 
tensor_mul = torch.mul(tensor, tensor)
tensor_mul

tensor([[1., 4., 9.],
        [1., 4., 9.]])

In [13]:
# Clamp is an important method that allows you to clamp your tensor values to a 
# certain minimum or maximum value
tensor_clamp = torch.clamp(tensor, min=-0.2, max=2)
tensor_clamp

tensor([[-0.2000, -0.2000, -0.2000],
        [ 1.0000,  2.0000,  2.0000]])

In [ ]:
# Can perform matrix operations as well such as dot product. 
t1 = torch.Tensor([1, 2])
t2 = torch.Tensor([10, 20])
dot_product = torch.dot(t1, t2) # Do it by hand to see (1)*(10) + (2)*(20) = 10 + 40 = 50
dot_product

tensor(50.)

In [ ]:
# Torch also allows you to work with multi dimension matrices and vectors
matrix = torch.Tensor([[1,2,3],
                       [4, 5, 6]])
vector = torch.Tensor([0, 1, 2])

# torch.mv will multiple the matrix by the corresponding vector
matrix_vector = torch.mv(matrix, vector) # Must be compatible sizes, this ex 2x3 * 3x1 
matrix_vector

tensor([ 8., 17.])

In [16]:
# Can also do matrix between two matrices with torch.mm method
another_matrix = torch.Tensor([[10, 30],
                               [20, 0],
                               [0, 50]])
matrix_mult = torch.mm(matrix, another_matrix)
matrix_mult

tensor([[ 50., 180.],
        [140., 420.]])

In [17]:
# Pretty much anything you can do in nunpy we can do here in tensors, and sped up with GPUs!

In [ ]:
# Arg max will find you largest value along particular dimension
torch.argmax(matrix_mult, dim=1) # (140)


tensor([1, 1])

In [25]:
torch.argmin(matrix_mult, dim=1)


tensor([0, 0])