In [1]:
import torch
print(torch.__version__)

2.9.1+cu128


In [2]:
initial_tensor = torch.rand(2, 3)
initial_tensor

tensor([[0.3322, 0.8282, 0.8268],
        [0.1899, 0.3188, 0.9620]])

In [ ]:
# Any operations that modify the tensor in-place have an '_' suffix
initial_tensor.fill_(10)
# Sometimes there is no function without the _, for example fill only is with that tensor

tensor([[10., 10., 10.],
        [10., 10., 10.]])

In [4]:
new_tesnor = initial_tensor.add(5)
new_tesnor

tensor([[15., 15., 15.],
        [15., 15., 15.]])

In [5]:
initial_tensor # Can see still all 10s

tensor([[10., 10., 10.],
        [10., 10., 10.]])

In [6]:
initial_tensor.add_(8)
initial_tensor

tensor([[18., 18., 18.],
        [18., 18., 18.]])

In [7]:
new_tesnor.sqrt_()
new_tesnor

tensor([[3.8730, 3.8730, 3.8730],
        [3.8730, 3.8730, 3.8730]])

In [8]:
# A lot of operation from numpy are similarily available in torch:
x = torch.linspace(start=0.1, end = 10.0, steps = 15)
x

tensor([ 0.1000,  0.8071,  1.5143,  2.2214,  2.9286,  3.6357,  4.3429,  5.0500,
         5.7571,  6.4643,  7.1714,  7.8786,  8.5857,  9.2929, 10.0000])

In [9]:
# Can chunk a tensor into different pieces like so: 
tensor_chunk = torch.chunk(x,3,0)
tensor_chunk

(tensor([0.1000, 0.8071, 1.5143, 2.2214, 2.9286]),
 tensor([3.6357, 4.3429, 5.0500, 5.7571, 6.4643]),
 tensor([ 7.1714,  7.8786,  8.5857,  9.2929, 10.0000]))

In [11]:
# Just like chunk, we can use concat to combine the pieces into one tensor
first_piece = tensor_chunk[0]
second_piece = tensor_chunk[1]
third_piece = tensor_chunk[2]

tensor_concat = torch.concat((first_piece, second_piece, third_piece), 0)
tensor_concat

tensor([ 0.1000,  0.8071,  1.5143,  2.2214,  2.9286,  3.6357,  4.3429,  5.0500,
         5.7571,  6.4643,  7.1714,  7.8786,  8.5857,  9.2929, 10.0000])

In [12]:
random_tensor = torch.Tensor([[10, 8, 30], [40, 5, 6], [12, 2, 21]])
random_tensor

tensor([[10.,  8., 30.],
        [40.,  5.,  6.],
        [12.,  2., 21.]])

In [13]:
# Can access elements just like numpy
random_tensor[0, 1]

tensor(8.)

In [14]:
# Can use array slicing as well
# Let's get all rows from 1 onward and all columns from 1 onward
random_tensor[1:, 1:]

tensor([[ 5.,  6.],
        [ 2., 21.]])

In [15]:
random_tensor.size() # Gives sides along each dimension

torch.Size([3, 3])

In [16]:
# Can use the view function to view, DOES NOT CREATE A NEW TENSOR
resized_tensor = random_tensor.view(9)
resized_tensor

tensor([10.,  8., 30., 40.,  5.,  6., 12.,  2., 21.])

In [ ]:
resized_tensor.size() # Now 9 along

torch.Size([9])

In [ ]:
random_tensor[2,2] = 100.0
resized_tensor # See resized now has 100, they share same underlying memory

tensor([ 10.,   8.,  30.,  40.,   5.,   6.,  12.,   2., 100.])

In [19]:
random_tensor

tensor([[ 10.,   8.,  30.],
        [ 40.,   5.,   6.],
        [ 12.,   2., 100.]])

In [21]:
random_tensor.shape # See the shape of our tensor

torch.Size([3, 3])

In [22]:
# Can change the shape by adding or removing dimensions
# Squeeze and unsqueeze operations are made for this

tensor_unsqueeze = torch.unsqueeze(random_tensor, 2)
tensor_unsqueeze

tensor([[[ 10.],
         [  8.],
         [ 30.]],

        [[ 40.],
         [  5.],
         [  6.]],

        [[ 12.],
         [  2.],
         [100.]]])

In [23]:
initial_tensor

tensor([[18., 18., 18.],
        [18., 18., 18.]])

In [24]:
tensor_transpose = torch.transpose(initial_tensor, 0, 1)
tensor_transpose

tensor([[18., 18.],
        [18., 18.],
        [18., 18.]])