In [2]:
import torch

print(torch.__version__)

2.9.1+cu128


In [3]:
# Default type for torch tensors are floats.
torch.set_default_dtype(torch.float64)
torch.get_default_dtype()
# Pytorch has a lot of CPU & GPU types, can visit https://pytorch.org/docs/stable/tensors.html

torch.float64

In [4]:
# Create a new torch tensor
tensor_arr = torch.Tensor([[1,2,3], [4,5,6]]) # .Tensor is default for float
tensor_arr


tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [5]:
torch.is_tensor(tensor_arr) # See if a type is a tensor

True

In [6]:
torch.numel(tensor_arr) # Prints the number of elements in a tensor no matter size or shape

6

In [7]:
tensor_uninitialized = torch.Tensor(2,2)
tensor_uninitialized

tensor([[0., 0.],
        [0., 0.]])

In [8]:
tensor_rand = torch.rand(2,2)
tensor_rand

tensor([[0.6935, 0.1652],
        [0.0031, 0.7707]])

In [ ]:
tensor_int = torch.Tensor([5,3]).type(torch.IntTensor) # Use int type for CPU
tensor_int

tensor([5, 3], dtype=torch.int32)

In [11]:
# Can also just create with the torch object itself, for example short tensor will be int16
tensor_short = torch.ShortTensor([5, 3])
tensor_short

tensor([5, 3], dtype=torch.int16)

In [12]:
# Can create and fill with value
tensor_fill = torch.full((2, 6), fill_value=10)
tensor_fill

tensor([[10, 10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10, 10]])

In [13]:
# Can use the like word to create tensors of same shape
tensor_of_ones = torch.ones([2, 4], dtype=torch.int32)
tensor_of_ones

tensor_of_zeroes = torch.zeros_like(tensor_of_ones)
tensor_of_zeroes

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)

In [14]:
# Make a n * n matrice with diagnol 1s
tensor_eye = torch.eye(5)
tensor_eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [15]:
# Can find where non-zero elements are in tensor like so: 
non_zero = torch.nonzero(tensor_eye)
non_zero

tensor([[0, 0],
        [1, 1],
        [2, 2],
        [3, 3],
        [4, 4]])

In [16]:
# How to make copy of tensor, List, numpy arr, etc
i = torch.tensor([[0, 1, 1], [2, 2, 0]])

In [17]:
v = torch.tensor([3, 4, 5], dtype=torch.float32)

In [19]:
spare_tensor = torch.sparse_coo_tensor(i, v, [2, 5])
# Constructs a sparse tensor in coordinate format with non-zero elements at indeces with the given values
spare_tensor.data

tensor(indices=tensor([[0, 1, 1],
                       [2, 2, 0]]),
       values=tensor([3., 4., 5.]),
       size=(2, 5), nnz=3, dtype=torch.float32, layout=torch.sparse_coo)